sudo: required

services:
  - docker

before_install:
  - docker version
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose

script:
  - docker-compose build
  - docker-compose up
